package com.cyf.xiaoxuedi.DO;

import java.math.BigDecimal;
import java.util.Date;

public class MissionDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission_info.id
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission_info.user_id
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission_info.title
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission_info.detail
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission_info.price
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission_info.location
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission_info.school
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission_info.status
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission_info.create_time
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission_info.update_time
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission_info.id
     *
     * @return the value of mission_info.id
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission_info.id
     *
     * @param id the value for mission_info.id
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission_info.user_id
     *
     * @return the value of mission_info.user_id
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission_info.user_id
     *
     * @param userId the value for mission_info.user_id
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission_info.title
     *
     * @return the value of mission_info.title
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission_info.title
     *
     * @param title the value for mission_info.title
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission_info.detail
     *
     * @return the value of mission_info.detail
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission_info.detail
     *
     * @param detail the value for mission_info.detail
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission_info.price
     *
     * @return the value of mission_info.price
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission_info.price
     *
     * @param price the value for mission_info.price
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission_info.location
     *
     * @return the value of mission_info.location
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission_info.location
     *
     * @param location the value for mission_info.location
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission_info.school
     *
     * @return the value of mission_info.school
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission_info.school
     *
     * @param school the value for mission_info.school
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission_info.status
     *
     * @return the value of mission_info.status
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission_info.status
     *
     * @param status the value for mission_info.status
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission_info.create_time
     *
     * @return the value of mission_info.create_time
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission_info.create_time
     *
     * @param createTime the value for mission_info.create_time
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission_info.update_time
     *
     * @return the value of mission_info.update_time
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission_info.update_time
     *
     * @param updateTime the value for mission_info.update_time
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}