package com.cyf.xiaoxuedi.DO;

import java.math.BigDecimal;
import java.util.Date;

public class OrderDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.id
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.user_id
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.accepter_id
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    private Integer accepterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.mission_id
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    private Integer missionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_price
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    private BigDecimal orderPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.status
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.create_time
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.update_time
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.id
     *
     * @return the value of order_info.id
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.id
     *
     * @param id the value for order_info.id
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.user_id
     *
     * @return the value of order_info.user_id
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.user_id
     *
     * @param userId the value for order_info.user_id
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.accepter_id
     *
     * @return the value of order_info.accepter_id
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    public Integer getAccepterId() {
        return accepterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.accepter_id
     *
     * @param accepterId the value for order_info.accepter_id
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    public void setAccepterId(Integer accepterId) {
        this.accepterId = accepterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.mission_id
     *
     * @return the value of order_info.mission_id
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    public Integer getMissionId() {
        return missionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.mission_id
     *
     * @param missionId the value for order_info.mission_id
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    public void setMissionId(Integer missionId) {
        this.missionId = missionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_price
     *
     * @return the value of order_info.order_price
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    public BigDecimal getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_price
     *
     * @param orderPrice the value for order_info.order_price
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    public void setOrderPrice(BigDecimal orderPrice) {
        this.orderPrice = orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.status
     *
     * @return the value of order_info.status
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.status
     *
     * @param status the value for order_info.status
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.create_time
     *
     * @return the value of order_info.create_time
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.create_time
     *
     * @param createTime the value for order_info.create_time
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.update_time
     *
     * @return the value of order_info.update_time
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.update_time
     *
     * @param updateTime the value for order_info.update_time
     *
     * @mbg.generated Fri Jul 31 13:59:07 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}