package com.cyf.xiaoxuedi.DO;

public class SequenceDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.name
     *
     * @mbg.generated Fri Jul 31 13:41:10 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.sequence
     *
     * @mbg.generated Fri Jul 31 13:41:10 CST 2020
     */
    private Integer sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.step
     *
     * @mbg.generated Fri Jul 31 13:41:10 CST 2020
     */
    private Integer step;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.init_number
     *
     * @mbg.generated Fri Jul 31 13:41:10 CST 2020
     */
    private Integer initNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.max_number
     *
     * @mbg.generated Fri Jul 31 13:41:10 CST 2020
     */
    private Integer maxNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.name
     *
     * @return the value of sequence_info.name
     *
     * @mbg.generated Fri Jul 31 13:41:10 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.name
     *
     * @param name the value for sequence_info.name
     *
     * @mbg.generated Fri Jul 31 13:41:10 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.sequence
     *
     * @return the value of sequence_info.sequence
     *
     * @mbg.generated Fri Jul 31 13:41:10 CST 2020
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.sequence
     *
     * @param sequence the value for sequence_info.sequence
     *
     * @mbg.generated Fri Jul 31 13:41:10 CST 2020
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.step
     *
     * @return the value of sequence_info.step
     *
     * @mbg.generated Fri Jul 31 13:41:10 CST 2020
     */
    public Integer getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.step
     *
     * @param step the value for sequence_info.step
     *
     * @mbg.generated Fri Jul 31 13:41:10 CST 2020
     */
    public void setStep(Integer step) {
        this.step = step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.init_number
     *
     * @return the value of sequence_info.init_number
     *
     * @mbg.generated Fri Jul 31 13:41:10 CST 2020
     */
    public Integer getInitNumber() {
        return initNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.init_number
     *
     * @param initNumber the value for sequence_info.init_number
     *
     * @mbg.generated Fri Jul 31 13:41:10 CST 2020
     */
    public void setInitNumber(Integer initNumber) {
        this.initNumber = initNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.max_number
     *
     * @return the value of sequence_info.max_number
     *
     * @mbg.generated Fri Jul 31 13:41:10 CST 2020
     */
    public Integer getMaxNumber() {
        return maxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.max_number
     *
     * @param maxNumber the value for sequence_info.max_number
     *
     * @mbg.generated Fri Jul 31 13:41:10 CST 2020
     */
    public void setMaxNumber(Integer maxNumber) {
        this.maxNumber = maxNumber;
    }
}