spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1976120322w
    url: jdbc:mysql://localhost:3307/xiaoxuedi
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapping/*.xml
#    ?characterEncoding=utf-8&useSSL=false