spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1976120322w
    url: jdbc:mysql://localhost:3307/xiaoxuedi
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    database: 10
    jedis:
      pool:
        max-active: 50
        min-idle: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
#    ?characterEncoding=utf-8&useSSL=false

# 配置Spring-boot对Redis的依赖
mq:
  nameserver:
    addr: 127.0.0.1:9876
  topic: status