package com.cyf.xiaoxuedi.DAO;

import com.cyf.xiaoxuedi.DO.MissionDO;

import java.util.List;

public interface MissionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_info
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_info
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    int insert(MissionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_info
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    int insertSelective(MissionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_info
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    MissionDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_info
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    int updateByPrimaryKeySelective(MissionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission_info
     *
     * @mbg.generated Thu Jul 30 17:19:41 CST 2020
     */
    int updateByPrimaryKey(MissionDO record);


    List<MissionDO> selectMissionBySchool(String school, Integer page);

    List<MissionDO> selectMyMissionByStatus(Integer userId, Byte status, Integer offset);

    int updateStatusByPrimaryKey(Byte status, Integer id);
}